version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: retail-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: retaildb
      MYSQL_USER: retailuser
      MYSQL_PASSWORD: retailpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - retail-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  retail-app:
    build: .
    container_name: retail-application
    environment:
      DB_USERNAME: retailuser
      DB_PASSWORD: retailpass
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - retail-network
    volumes:
      - app_logs:/var/log
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  mysql_data:
  app_logs:

networks:
  retail-network:
    driver: bridge