pipeline {
    agent any

    tools {
        jdk 'jdk21'
        maven 'maven3'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/shadow-phantom-sys/BigB.git'
            }
        }

        stage('Build') {
    steps {
        dir('BB') {   // 👈 cd into BB first
            sh './mvnw clean install'
        }
    }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Package') {
            steps {
                sh 'mvn package -DskipTests'
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deployment step (can be Docker, Kubernetes, or server copy)'
            }
        }
    }

    post {
        success {
            echo 'Build and Tests passed successfully!'
        }
        failure {
            echo 'Build Failed. Check logs.'
        }
    }
}